export interface ModelConfig {
  id: string;
  label: string;
  dataModel: string;
  icon?: string;
  description: string;
  featured?: boolean;
  // Composer controls
  showUploadButton: boolean;
  showQuantity: boolean;
  quantityDefault?: number;
  quantityMax?: number;
  showAspectRatio: boolean;
  aspectRatioOptions?: string[];
  aspectRatioDefault?: string;
  showQuality?: boolean;
  qualityOptions?: string[];
  qualityDefault?: string;
  showResolution: boolean;
  resolutionOptions?: string[];
  resolutionDefault?: string;
  showVectorMode?: boolean;
  showColorTransfer?: boolean;
  showEnhance?: boolean;
  showCharacterCard?: boolean;
  showStyleCard?: boolean;
  showAdvancedSettings?: boolean;
  showDrawButton?: boolean;
  cost: number;
}

export const MODEL_CONFIGS: Record<string, ModelConfig> = {
  "nano-banana-pro": {
    id: "nano-banana-pro",
    label: "Nano Banana Pro",
    dataModel: "nano_banana_2",
    description: "Google's flagship generation model",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    aspectRatioOptions: ["1:1", "3:4", "4:3", "16:9"],
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    showDrawButton: true,
    cost: 1,
  },
  "seedream-5-lite": {
    id: "seedream-5-lite",
    label: "Seedream 5.0 lite",
    dataModel: "seedream_v5_lite",
    description: "Intelligent visual reasoning",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "21:9",
    aspectRatioOptions: ["1:1", "21:9", "16:9"],
    showQuality: true,
    qualityDefault: "4K",
    qualityOptions: ["2K", "3K", "4K"],
    showResolution: true,
    resolutionDefault: "4K",
    resolutionOptions: ["2K", "4K"],
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 1,
  },
  "seedream-4-5": {
    id: "seedream-4-5",
    label: "Seedream 4.5",
    dataModel: "seedream_v4_5",
    description: "ByteDance's next-gen 4K image model",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 4,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:2",
    aspectRatioOptions: ["3:2", "2:3", "1:1"],
    showResolution: true,
    resolutionDefault: "2K",
    resolutionOptions: ["2K", "4K"],
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 4,
  },
  "recraft-v4-1": {
    id: "recraft-v4-1",
    label: "Recraft V4.1",
    dataModel: "recraft-v4-1",
    description: "Photorealistic and expressive image generation",
    featured: true,
    showUploadButton: false,
    showQuantity: true,
    quantityDefault: 4,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "9:16",
    aspectRatioOptions: ["1:1", "9:16", "16:9", "3:4"],
    showResolution: true,
    resolutionDefault: "Pro",
    resolutionOptions: ["Standard", "Pro"],
    showVectorMode: true,
    showColorTransfer: true,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 32,
  },
  "recraft-v4-1-utility": {
    id: "recraft-v4-1-utility",
    label: "Recraft V4.1 Utility",
    dataModel: "recraft-v4-1-utility",
    description: "Simple scenes with flat, even lighting",
    showUploadButton: false,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "1:1",
    aspectRatioOptions: ["1:1", "9:16", "16:9", "3:4"],
    showResolution: true,
    resolutionDefault: "Standard",
    resolutionOptions: ["Standard", "Pro"],
    showVectorMode: true,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 16,
  },
  "soul-2-0": {
    id: "soul-2-0",
    label: "Soul 2.0",
    dataModel: "soul-v2",
    description: "Next generation ultra-realistic fashion visuals",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    aspectRatioOptions: ["3:4", "1:1", "4:3"],
    showResolution: true,
    resolutionDefault: "2K",
    resolutionOptions: ["2K", "4K"],
    showVectorMode: false,
    showColorTransfer: true,
    showEnhance: true,
    showCharacterCard: true,
    showStyleCard: true,
    cost: 0.125,
  },
  "soul-cinema": {
    id: "soul-cinema",
    label: "Soul Cinema",
    dataModel: "soul-cinematic",
    description: "Cinema-grade visual creation",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "16:9",
    aspectRatioOptions: ["16:9", "21:9", "3:4"],
    showResolution: true,
    resolutionDefault: "2K",
    resolutionOptions: ["2K", "4K"],
    showVectorMode: false,
    showColorTransfer: true,
    showEnhance: false,
    showCharacterCard: true,
    showStyleCard: true,
    cost: 0.125,
  },
  "gpt-image-2": {
    id: "gpt-image-2",
    label: "GPT Image 2",
    dataModel: "imagegen_2_0",
    description: "4K images with near-perfect text rendering",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "1:1",
    showResolution: true,
    resolutionDefault: "2K",
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 4,
  },
  "flux-2-pro": {
    id: "flux-2-pro",
    label: "FLUX.2 Pro",
    dataModel: "flux_2",
    description: "Speed-optimized detail",
    featured: true,
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 2,
  },
  "nano-banana": {
    id: "nano-banana",
    label: "Nano Banana",
    dataModel: "nano_banana",
    description: "Google's standard generation model",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 1,
  },
  "soul": {
    id: "soul",
    label: "Higgsfield Soul",
    dataModel: "soul",
    description: "Ultra-realistic fashion visuals",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 0.125,
  },
  "multi-reference": {
    id: "multi-reference",
    label: "Multi Reference",
    dataModel: "multi",
    description: "Multiple edits in one shot",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "2:3",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 2,
  },
  "gpt-image": {
    id: "gpt-image",
    label: "GPT Image",
    dataModel: "gpt",
    description: "Versatile text-to-image AI",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "1:1",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 3,
  },
  "flux-2-flex": {
    id: "flux-2-flex",
    label: "FLUX.2 Flex",
    dataModel: "flux-flex",
    description: "Next-gen image generation",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    showAdvancedSettings: true,
    cost: 2,
  },
  "flux-2-max": {
    id: "flux-2-max",
    label: "FLUX.2 Max",
    dataModel: "flux-max",
    description: "Ultimate precision and speed",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 4,
  },
  "kling-o1": {
    id: "kling-o1",
    label: "Kling O1",
    dataModel: "kling-o1-image",
    description: "Kling's Photorealistic Image Model",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "9:16",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 2,
  },
  "z-image": {
    id: "z-image",
    label: "Z-Image",
    dataModel: "z-image",
    description: "Instant lifelike portraits",
    showUploadButton: false,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "1:1",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 1,
  },
  "nano-banana-2-lite": {
    id: "nano-banana-2-lite",
    label: "Nano Banana 2 Lite",
    dataModel: "nano_banana_2_lite",
    description: "Lightweight image generation at speed",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 0.5,
  },
  "nano-banana-2": {
    id: "nano-banana-2",
    label: "Nano Banana 2",
    dataModel: "nano_banana_flash",
    description: "Pro quality at Flash speed",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "3:4",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 1,
  },
  "reve": {
    id: "reve",
    label: "Reve",
    dataModel: "reve",
    description: "Advanced image editing model",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "1:1",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 1.5,
  },
  "wan-2-2": {
    id: "wan-2-2",
    label: "WAN 2.2",
    dataModel: "wan_2_2",
    description: "High-fidelity cinematic visuals",
    showUploadButton: true,
    showQuantity: true,
    quantityDefault: 1,
    quantityMax: 4,
    showAspectRatio: true,
    aspectRatioDefault: "16:9",
    showResolution: false,
    showVectorMode: false,
    showColorTransfer: false,
    showEnhance: false,
    showCharacterCard: false,
    showStyleCard: false,
    cost: 2,
  },
};

export const FEATURED_MODELS = Object.values(MODEL_CONFIGS).filter(m => m.featured);
export const ALL_MODELS = Object.values(MODEL_CONFIGS);
