import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthModalProvider } from "@/context/AuthModalContext";
import ProfileSynchronizer from "@/components/auth/ProfileSynchronizer";
import CinefieldAuthModal from "@/components/auth/CinefieldAuthModal";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AuthModalProvider>
        <ProfileSynchronizer />
        <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
          <body className="min-h-full flex flex-col">
            {children}
            {/* <CinefieldAuthModal /> */}
          </body>
        </html>
      </AuthModalProvider>
    </ClerkProvider>
  );
}
