import "server-only";

/**
 * Cinefield EventPublisher — the transport boundary for domain events
 * (Phase 6R.2).
 *
 * An event reports something that ALREADY HAPPENED and is immutable
 * ("generation.completed", "attempt.submitted"). It is the counterpart to a
 * command, which asks for work that has not happened yet (command-bus.ts).
 * Events have zero or many consumers and none of them may change the
 * outcome — a publisher never waits on a consumer.
 *
 * WHY THIS EXISTS
 * The locked Phase 6R architecture puts Kafka/Amazon MSK under the event
 * backbone, fed by a PostgreSQL transactional outbox. Domain code must not
 * import a Kafka SDK: the correctness guarantee comes from the outbox (the
 * event row is written in the SAME transaction as the state change, so an
 * event can never disagree with the database), while Kafka is only the
 * transport that carries it onward. Keeping that split behind this interface
 * is what makes the transport replaceable without touching domain logic.
 *
 * WHAT MAY TRAVEL IN AN EVENT
 * Identifiers, enums, timestamps, numbers. Never a secret, an authorization
 * header, a signed URL, a temporary provider URL, a raw provider payload, or
 * a user prompt. Events are retained, replayed and read by many consumers —
 * anything put in one should be treated as permanently disclosed internally.
 *
 * DELIVERY SEMANTICS
 * At-least-once. Consumers must deduplicate on `eventId`.
 */

/** Event families named by the master roadmap. One topic/stream per family. */
export type EventFamily =
  | "generation"
  | "provider"
  | "asset"
  | "billing"
  | "credit"
  | "security"
  | "audit";

/**
 * A published domain event.
 *
 * `eventId` is generated by the producer and is the consumer's deduplication
 * key. `occurredAt` is when the fact became true, not when it was published.
 * `payload` is intentionally an open record: each family will get a schema in
 * Phase 6R.15 (Glue Schema Registry) rather than a TypeScript union that
 * would have to be edited for every new event.
 */
export interface DomainEvent {
  eventId: string;
  family: EventFamily;
  /** Dotted name within the family, e.g. "generation.completed". */
  type: string;
  /** Ordering/partition key. Events for one generation stay in order. */
  aggregateId: string;
  occurredAt: string;
  traceId?: string;
  payload: Record<string, unknown>;
}

export interface EventPublisher {
  /**
   * Records the event for delivery.
   *
   * The outbox implementation (Phase 6R.9) takes a transaction handle so the
   * event row commits atomically with the state change that produced it. That
   * parameter is deliberately absent from this interface until the outbox
   * exists, so no caller writes code today that assumes a transaction shape
   * we have not built.
   */
  publish(event: DomainEvent): Promise<void>;
}

/**
 * The only adapter that exists in Phase 6R.2.
 *
 * It records the event and returns — no outbox row, no Kafka. It exists so
 * the contract can be wired and type-checked before Postgres outbox
 * (Phase 6R.9) and MSK exist. Nothing in production may rely on it.
 */
export class NoopEventPublisher implements EventPublisher {
  readonly published: DomainEvent[] = [];

  async publish(event: DomainEvent): Promise<void> {
    this.published.push(event);
    console.info(
      "[cinefield:event]",
      JSON.stringify({
        family: event.family,
        type: event.type,
        aggregateId: event.aggregateId,
        eventId: event.eventId,
        adapter: "noop",
      })
    );
  }
}

let publisher: EventPublisher | null = null;

/**
 * Process-wide EventPublisher. Phase 6R.9 swaps in the outbox-backed
 * implementation via `setEventPublisher`; callers never change.
 */
export function getEventPublisher(): EventPublisher {
  if (!publisher) publisher = new NoopEventPublisher();
  return publisher;
}

export function setEventPublisher(next: EventPublisher): void {
  publisher = next;
}
