import type { VerifiedMime } from "@/lib/media/mime-detect";

/**
 * Content provenance contract (Phase 27-A).
 *
 * ---------------------------------------------------------------------------
 * GENERATED-MEDIA PROVENANCE — NOT SOFTWARE BUILD PROVENANCE
 * ---------------------------------------------------------------------------
 * The roadmap's Phase 27 handoff says it in one line: "Phase 9 media pipeline
 * üzerine content provenance/C2PA signing/AI labeling eklenir; **artifact
 * provenance ile karıştırılmaz**." Phase 24 attests the SBOM of the software
 * that runs Cinefield. This package attests the MEDIA that software produced.
 * They share no table, no signer, no identity, and no verification path, and
 * a test enforces that separation.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS IS HONESTLY NOT
 * ---------------------------------------------------------------------------
 * This is NOT an embedded C2PA manifest. The roadmap places the signing step
 * at "FFmpeg sonrası, R2 öncesi" — after FFmpeg, before R2 — and that
 * position does not exist yet: Phase 9-C (derived variants / FFmpeg) is
 * unbuilt, there is no `worker/media-worker.ts`, and no ffmpeg or c2patool
 * binding is a dependency of this repository. Writing an embed step with
 * nowhere to run would be the built-but-unwired defect this codebase has
 * closed repeatedly.
 *
 * What this package does instead is the part that IS provable today:
 * DETACHED provenance evidence, cryptographically bound to the SAME
 * `checksum_sha256` Phase 9-B already computes over the canonical bytes in
 * its sandbox. `ProvenanceMarkingState` keeps the distinction explicit and
 * unfakeable — `EMBEDDED_C2PA` is a state no code path in this repository
 * can currently produce.
 */

/**
 * IPTC DigitalSourceType vocabulary (cv.iptc.org/newscodes/digitalsourcetype).
 *
 * The machine-readable half of AI Act Article 50(2). Bounded to the three
 * terms that can describe a Cinefield output — this is a controlled
 * vocabulary, and inventing a fourth value would make the assertion
 * unverifiable by any standard reader.
 */
export type DigitalSourceType =
  /** Wholly generated by a trained model. The ordinary Cinefield output. */
  | "trainedAlgorithmicMedia"
  /** Generated content composited with real captured material (reference images). */
  | "compositeWithTrainedAlgorithmicMedia"
  /** Produced by a non-trained algorithm (procedural). Not currently produced. */
  | "algorithmicMedia";

export const DIGITAL_SOURCE_TYPE_BASE = "http://cv.iptc.org/newscodes/digitalsourcetype/";

export function digitalSourceTypeUri(kind: DigitalSourceType): string {
  return `${DIGITAL_SOURCE_TYPE_BASE}${kind}`;
}

/**
 * How far marking actually got for one asset. Ordered weakest to strongest.
 *
 * `EMBEDDED_C2PA` exists in the type so the eventual Phase 9-C sign step has
 * a state to write, and so this file states plainly that it is not reachable
 * today. Nothing in `src/` constructs it — asserted by test.
 */
export type ProvenanceMarkingState =
  /** No provenance evidence exists for this asset. */
  | "NOT_MARKED"
  /** A manifest was built and stored, but nothing signed it. */
  | "EVIDENCE_RECORDED"
  /** A detached ES256 signature binds the manifest to the content digest. */
  | "SIGNED_DETACHED"
  /** A C2PA manifest is embedded in the delivered bytes. NOT REACHABLE YET. */
  | "EMBEDDED_C2PA";

export const PROVENANCE_MARKING_STATES: readonly ProvenanceMarkingState[] = [
  "NOT_MARKED",
  "EVIDENCE_RECORDED",
  "SIGNED_DETACHED",
  "EMBEDDED_C2PA",
];

/** Marking states that count as "marked" for 27-D's coverage metric. */
export const MARKED_STATES: ReadonlySet<ProvenanceMarkingState> = new Set([
  "EVIDENCE_RECORDED",
  "SIGNED_DETACHED",
  "EMBEDDED_C2PA",
]);

/**
 * AI Act Article 50(4) — the VISIBLE deepfake label.
 *
 * The roadmap is precise about who owes what: "Madde 50/2 (makine-okunur
 * işaret) provider yükümlülüğüdür; Madde 50/4 (görünür deepfake etiketi)
 * deployer yükümlülüğüdür." Cinefield is the provider, so 50(2) is ours and
 * this package implements it. 50(4) falls on the deployer (the user), is
 * transferred contractually via ToS/AUP — Phase 29's ownership, not this
 * file's — and Cinefield's job is to PROVIDE the mechanism.
 *
 * So this enum records a technical requirement flag, never a legal
 * conclusion. Nothing here decides whether content IS a deepfake: no
 * deepfake classifier exists in this repository (`MODERATION_ENGINE` is
 * `null`, Phase 9-B), and Phase 28 owns Trust & Safety classification.
 */
export type DisclosureRequirement =
  /** Ordinary/fictional content — the roadmap: "Sıradan/kurgusal içerikte görünür etiket gerekmez." */
  | "NONE_REQUIRED"
  /** Flagged as depicting a real person/deepfake; a visible label is owed by the deployer. */
  | "VISIBLE_LABEL_REQUIRED"
  /** No classifier has spoken. Never treated as NONE_REQUIRED — see fail-closed below. */
  | "NOT_ASSESSED";

export const DISCLOSURE_REQUIREMENTS: readonly DisclosureRequirement[] = [
  "NONE_REQUIRED",
  "VISIBLE_LABEL_REQUIRED",
  "NOT_ASSESSED",
];

/**
 * The C2PA manifest Cinefield builds, matching the roadmap's own literal
 * template (Phase 27, "Nasıl yapılacak" step 2) field for field.
 *
 * Deliberately narrow: `claim_generator` plus exactly one `c2pa.actions`
 * assertion. Every field is a bounded identifier or a controlled-vocabulary
 * URI — there is nowhere in this shape to put a prompt, a provider payload,
 * a signed URL, an object key, or a credential.
 */
export interface C2paAction {
  readonly action: "c2pa.created";
  readonly digitalSourceType: string;
  readonly softwareAgent: string;
}

export interface C2paActionsAssertion {
  readonly label: "c2pa.actions";
  readonly data: { readonly actions: readonly C2paAction[] };
}

export interface C2paManifest {
  readonly claim_generator: string;
  readonly assertions: readonly C2paActionsAssertion[];
}

/**
 * What a verification pass can conclude. Fail-closed by construction: only
 * `VERIFIED` means "this evidence provably binds to these bytes", and it is
 * reachable ONLY when a signature exists, the signer is trusted, and the
 * digest matches. Every uncertainty has its own distinct state so that "we
 * could not check" can never be rendered as "it is fine" — the same
 * discipline `RestoreValidationState` (Phase 15-C) and `HealthStatus`
 * (Phase 13) already use.
 */
export type ProvenanceVerificationOutcome =
  | "VERIFIED"
  | "DIGEST_MISMATCH"
  | "INVALID_SIGNATURE"
  | "UNTRUSTED_SIGNER"
  | "SIGNER_UNAVAILABLE"
  | "MISSING_EVIDENCE"
  | "UNSUPPORTED_FORMAT"
  | "UNAVAILABLE";

export const PROVENANCE_VERIFICATION_OUTCOMES: readonly ProvenanceVerificationOutcome[] = [
  "VERIFIED",
  "DIGEST_MISMATCH",
  "INVALID_SIGNATURE",
  "UNTRUSTED_SIGNER",
  "SIGNER_UNAVAILABLE",
  "MISSING_EVIDENCE",
  "UNSUPPORTED_FORMAT",
  "UNAVAILABLE",
];

/** Exactly one member. Nothing upgrades into it by omission. */
export const PROVENANCE_SUCCESS_OUTCOMES: ReadonlySet<ProvenanceVerificationOutcome> = new Set([
  "VERIFIED",
]);

export function isProvenanceVerified(outcome: ProvenanceVerificationOutcome): boolean {
  return PROVENANCE_SUCCESS_OUTCOMES.has(outcome);
}

/**
 * Which delivered formats a real C2PA manifest could be EMBEDDED into.
 *
 * The roadmap names c2patool's own support: "c2patool mp4/jpg/png/wav
 * destekler". Everything Cinefield can currently store but c2patool cannot
 * carry is `SIDECAR_ONLY` — honestly, per format, rather than one fabricated
 * uniform claim. Nothing is `EMBEDDED_SUPPORTED` in the sense of "we do it";
 * this matrix says only what the FORMAT could carry once the Phase 9-C sign
 * step exists.
 */
export type FormatProvenanceSupport = "EMBED_CAPABLE" | "SIDECAR_ONLY";

export const FORMAT_PROVENANCE_SUPPORT: Readonly<Record<VerifiedMime, FormatProvenanceSupport>> = {
  "image/jpeg": "EMBED_CAPABLE",
  "image/png": "EMBED_CAPABLE",
  "video/mp4": "EMBED_CAPABLE",
  "audio/wav": "EMBED_CAPABLE",
  // c2patool does not carry a manifest in these containers today. Detached
  // evidence still binds to their digest — it simply cannot travel inside
  // the file, which is exactly the durability limitation the roadmap's own
  // "Dürüst dayanıklılık uyarısı" describes for every format anyway.
  "image/webp": "SIDECAR_ONLY",
  "image/gif": "SIDECAR_ONLY",
  "image/avif": "SIDECAR_ONLY",
  "video/webm": "SIDECAR_ONLY",
  "audio/mpeg": "SIDECAR_ONLY",
};

export function formatSupport(mime: string): FormatProvenanceSupport | null {
  return Object.prototype.hasOwnProperty.call(FORMAT_PROVENANCE_SUPPORT, mime)
    ? FORMAT_PROVENANCE_SUPPORT[mime as VerifiedMime]
    : null;
}

/**
 * The durable evidence record for one media asset.
 *
 * Bounded by construction. Note what is ABSENT and permanently so: no
 * prompt, no negative prompt, no provider payload, no object key, no signed
 * URL, no bucket, no token, no `clerk_user_id`. Ownership is reachable by
 * joining `media_assets` — duplicating a personal identifier here would put
 * one more copy of it inside Phase 23's deletion blast radius for no gain.
 */
export interface ProvenanceEvidence {
  readonly mediaAssetId: string;
  readonly generationId: string | null;
  readonly attemptId: string | null;
  readonly markingState: ProvenanceMarkingState;
  readonly digitalSourceType: DigitalSourceType;
  readonly claimGenerator: string;
  readonly softwareAgent: string;
  /** The Phase 9-B SHA-256 over canonical bytes. Never recomputed here. */
  readonly contentDigestSha256: string;
  readonly verifiedMime: string;
  readonly formatSupport: FormatProvenanceSupport;
  readonly manifestVersion: string;
  /** Base64 ES256 signature over the canonical claim. Null when unsigned. */
  readonly signature: string | null;
  /** Bounded key identifier — NEVER key material. Null when unsigned. */
  readonly signerKeyId: string | null;
  readonly disclosureRequirement: DisclosureRequirement;
  readonly createdAt: string;
}

/** The manifest template version this package emits. Bump on shape change. */
export const MANIFEST_VERSION = "cinefield-c2pa-1";

/** Roadmap's literal value: `"claim_generator": "cinefield/1.0"`. */
export const CLAIM_GENERATOR = "cinefield/1.0";
