import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

/**
 * Cinefield generated API types (Phase 20-C).
 *
 * Reads `openapi/cinefield.json` (itself generated by
 * `scripts/generate-openapi.ts` from the real event-schema registry plus a
 * hand-verified HTTP path subset — see that script's header) and emits
 * `src/lib/contracts/generated/api-types.ts`. This is the "API tipleri
 * şemadan otomatik üretiliyor" (API types are auto-generated from the
 * schema) done-criterion made real: the generated file is never hand-edited,
 * and `contract-ci.yml` fails a PR that edited it directly by regenerating
 * and diffing.
 *
 * `openapi-typescript` (MIT, no network access needed for a local file
 * input, no paid service) is a pure static-analysis code generator — it
 * does not call any API and does not require the AWS Glue Schema Registry
 * to be live.
 */

const ROOT = process.cwd();
const INPUT_PATH = path.join(ROOT, "openapi", "cinefield.json");
const OUTPUT_PATH = path.join(ROOT, "src", "lib", "contracts", "generated", "api-types.ts");

const HEADER = `/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Produced by \`npm run contracts:generate-types\` from \`openapi/cinefield.json\`
 * (itself produced by \`npm run contracts:generate-openapi\` from
 * \`src/lib/events/event-schemas.ts\`). Edit the source schema, not this file —
 * \`contract-ci.yml\` (Phase 20-D) regenerates and diffs on every PR that
 * touches either input and fails the build on drift.
 */
`;

async function main(): Promise<void> {
  const schema = JSON.parse(readFileSync(INPUT_PATH, "utf8"));
  const ast = await openapiTS(schema);
  const output = astToString(ast);

  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, `${HEADER}\n${output}`, "utf8");
  console.log(`generate-api-types: wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
}

main().catch((error) => {
  console.error("generate-api-types: failed", error);
  process.exit(1);
});
