/**
 * Phase 27 / 9-C closure proof: produce a real signed artifact and verify it
 * with the OFFICIAL ContentAuth library.
 *
 * This script is the evidence 27-A's done criterion asks for — "Örnek çıktı
 * verify aracında valid provenance gösteriyor." It uses only synthetic media
 * generated by FFmpeg (a solid colour frame, a sine tone): no user media, no
 * production asset, no third-party copyrighted input.
 *
 * It signs with the official library's own development certificate, which the
 * C2PA ecosystem does NOT trust in production. That is stated in the output
 * rather than glossed: this proves the MECHANISM end to end, not public trust.
 *
 * Run:  npx tsx scripts/verify-c2pa-sample.ts
 */

import { execFile } from "node:child_process";
import { mkdtemp, rm, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { embedC2paProvenance, readEmbeddedProvenance, setC2paSignerMode } from "../src/lib/provenance/c2pa-embedder";

const FFMPEG = process.env.CINEFIELD_FFMPEG_PATH || "ffmpeg";

function ffmpeg(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    execFile(FFMPEG, args, { timeout: 60_000, windowsHide: true }, (error) =>
      error ? reject(error) : resolve()
    );
  });
}

interface Case {
  readonly label: string;
  readonly mime: string;
  readonly file: string;
  readonly makeArgs: (out: string) => string[];
}

const CASES: readonly Case[] = [
  {
    label: "image/png",
    mime: "image/png",
    file: "sample.png",
    makeArgs: (out) => ["-y", "-f", "lavfi", "-i", "color=c=blue:s=64x64:d=1", "-frames:v", "1", out],
  },
  {
    label: "image/jpeg",
    mime: "image/jpeg",
    file: "sample.jpg",
    makeArgs: (out) => ["-y", "-f", "lavfi", "-i", "color=c=green:s=64x64:d=1", "-frames:v", "1", out],
  },
  {
    label: "video/mp4",
    mime: "video/mp4",
    file: "sample.mp4",
    makeArgs: (out) => [
      "-y", "-f", "lavfi", "-i", "color=c=red:s=64x64:d=1",
      "-c:v", "libx264", "-pix_fmt", "yuv420p", out,
    ],
  },
  {
    label: "audio/wav",
    mime: "audio/wav",
    file: "sample.wav",
    makeArgs: (out) => ["-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=1", out],
  },
];

async function main(): Promise<void> {
  setC2paSignerMode("test");
  const dir = await mkdtemp(join(tmpdir(), "cinefield-c2pa-proof-"));
  let failures = 0;

  try {
    console.log("Phase 27 / 9-C — official C2PA verification proof");
    console.log("Signer: c2pa-node createTestSigner() — DEVELOPMENT certificate,");
    console.log("        NOT a production trust-list identity.\n");

    for (const testCase of CASES) {
      const path = join(dir, testCase.file);
      await ffmpeg(testCase.makeArgs(path));
      const bytes = new Uint8Array(await readFile(path));

      const embedded = await embedC2paProvenance({
        bytes,
        mime: testCase.mime,
        digitalSourceType: "trainedAlgorithmicMedia",
        softwareAgent: "Cinefield (model via provider)",
      });

      if (!embedded.ok) {
        console.log(`${testCase.label.padEnd(12)} EMBED FAILED (${embedded.reasonCode})`);
        failures += 1;
        continue;
      }

      const digest = createHash("sha256").update(embedded.bytes).digest("hex");
      const verified = await readEmbeddedProvenance({ bytes: embedded.bytes, mime: testCase.mime });

      if (!verified.present || !verified.valid) {
        console.log(`${testCase.label.padEnd(12)} OFFICIAL VERIFY FAILED`);
        failures += 1;
        continue;
      }

      console.log(`${testCase.label.padEnd(12)} EMBED OK -> OFFICIAL VERIFY: VALID`);
      console.log(`             bytes        ${bytes.byteLength} -> ${embedded.bytes.byteLength}`);
      console.log(`             sha256       ${digest}`);
      console.log(`             generator    ${verified.claimGenerator}`);
      console.log(`             issuer       ${verified.signerIssuer}`);
      console.log(`             sourceType   ${verified.digitalSourceType}`);

      // ---- Tamper: flip one byte in the delivered artifact ---------------
      const tampered = Uint8Array.from(embedded.bytes);
      tampered[tampered.length - 30] ^= 0xff;
      const tamperResult = await readEmbeddedProvenance({ bytes: tampered, mime: testCase.mime });
      const tamperDetected =
        !tamperResult.present || (tamperResult.present && !tamperResult.valid);
      console.log(
        `             tamper       ${tamperDetected ? "DETECTED" : "NOT DETECTED (!)"}` +
          (tamperResult.present && !tamperResult.valid
            ? ` ${JSON.stringify(tamperResult.validationCodes)}`
            : "")
      );
      if (!tamperDetected) failures += 1;
      console.log("");
    }

    if (failures > 0) {
      console.log(`FAILURES: ${failures}`);
      process.exitCode = 1;
    } else {
      console.log("All formats embedded and officially verified. Tamper detected in every case.");
    }
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

void main();
